baseURL = "https://tinygo-org.github.io/tinygo-site/"
languageCode = "en-us"
title = "TinyGo"
theme = "learn"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
