# netlify.toml

[[redirects]]
  from = "/bluetooth"
  to = "https://github.com/tinygo-org/bluetooth#go-bluetooth"
  status = 200

[[redirects]]
  from = "https://bluetooth.tinygo.org"
  to = "https://github.com/tinygo-org/bluetooth#go-bluetooth"
  status = 200
